# Sample notebook

This notebook is used to demonstrate connecting to Snowflake, within a codespaced environment. You would want to adopt this approach, as it uses
the pre-configured snowflake connection information that are used by the existing artifacts like streamlit app / sql scripts etc..

The below cell is the main initialization cell, every notebook should have this cell as it initializes the Snowflake connection and sets up the 
'sp_session' Snowpark session variable.

In [4]:

from IPython.display import display, HTML, Image , Markdown
from snowflake.snowpark.session import Session
import snowflake.snowpark.types as T
import snowflake.snowpark.functions as F
import os ,configparser ,json ,logging

# Import the commonly defined utility scripts using
# dynamic path include
import sys
sys.path.append('../python/lutils')
import sflk_base as L

display(Markdown("### Initialization"))
logging.basicConfig(stream=sys.stdout, level=logging.ERROR)

# Source various helper functions
%run ./scripts/notebook_helpers.py

# Define the project home directory, this is used for locating the config.ini file
PROJECT_HOME_DIR = '../../'
config = L.get_config(PROJECT_HOME_DIR)
sp_session = L.connect_to_snowflake(PROJECT_HOME_DIR)

if(sp_session == None):
    raise Exception(f'Unable to connect to snowflake. Validate connection information ')

sp_session.use_role(f'''{config['SNOW_CONN']['role']}''')
sp_session.use_schema(f'''{config['SNOW_CONN']['database']}.{config['SNOW_CONN']['schema']}''')
sp_session.use_warehouse(f'''{config['SNOW_CONN']['warehouse']}''')

df = sp_session.sql('select current_user() ,current_role() ,current_database() ,current_schema();').to_pandas()
display(df)

### Initialization

  CURRENT_USER() CURRENT_ROLE()     CURRENT_DATABASE() CURRENT_SCHEMA()
0         VSEKAR         PUBLIC  SNOWFLAKE_SAMPLE_DATA   TPCDS_SF100TCL

In [2]:
#Load data from table

store_sdf = sp_session.table('STORE').limit(5)
display(store_sdf.to_pandas())

,S_STORE_SK,S_STORE_ID,S_REC_START_DATE,S_REC_END_DATE,S_CLOSED_DATE_SK,S_STORE_NAME,S_NUMBER_EMPLOYEES,S_FLOOR_SPACE,S_HOURS,S_MANAGER,...,S_STREET_NAME,S_STREET_TYPE,S_SUITE_NUMBER,S_CITY,S_COUNTY,S_STATE,S_ZIP,S_COUNTRY,S_GMT_OFFSET,S_TAX_PRECENTAGE
0,1,AAAAAAAABAAAAAAA,1997-03-13,None,2451189.0,ought,245,5250760,8AM-4PM,William Ward,...,Spring,Wy,Suite 250,Garland,Walker County,AL,38767,United States,-6.0,0.03
1,2,AAAAAAAACAAAAAAA,1997-03-13,2000-03-12,NaN,able,236,5285950,8AM-4PM,Scott Smith,...,Sycamore,Dr.,Suite 410,York,Fulton County,GA,30236,United States,-5.0,0.03
2,3,AAAAAAAACAAAAAAA,2000-03-13,None,NaN,able,236,7557959,8AM-4PM,Scott Smith,...,Park Laurel,Road,Suite T,Boyd,Seward County,NE,60163,United States,-7.0,0.03
3,4,AAAAAAAAEAAAAAAA,1997-03-13,1999-03-13,2451044.0,ese,218,9341467,8AM-4PM,Edwin Adams,...,Lake,Ln,Suite 260,Johnstown,Oglethorpe County,GA,39785,United States,-5.0,0.03
4,5,AAAAAAAAEAAAAAAA,1999-03-14,2001-03-12,2450910.0,anti,288,9078805,8AM-4PM,Edwin Adams,...,Lee 6th,Court,Suite 80,Columbus,Boone County,KY,43622,United States,-6.0,0.03

--- 
### Closeout

In [3]:
sp_session.close()
print('Finished!!!')

Finished!!!